server:
  port: 8086
spring:
  application:
    name: employees
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      database: employees-db
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            jdbc:
              DataSourceAutoConfiguration:
