server:
  port: 8086
spring:
  application:
    name: employee
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:5432/postgres?currentSchema=employees_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
